# Generated by Django 6.0.2 on 2026-02-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('registration_for', models.CharField(choices=[('BNI_THALAIVAS', 'BNI Members - Thalaivas'), ('BNI_CHETTINAD', 'BNI Members - Chettinad'), ('BNI_MADURAI', 'BNI Members - Madurai'), ('PUBLIC', 'Public'), ('STUDENTS', 'Students')], max_length=20)),
                ('payment_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
