# Generated by Django 6.0.2 on 2026-02-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='event_logos/')),
                ('event_name', models.CharField(default='BNI Event', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Settings',
                'verbose_name_plural': 'Event Settings',
            },
        ),
    ]
