# Generated by Django 6.0.2 on 2026-02-08 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_registration_amount_registration_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('SCAN_SUCCESS', 'Scan Success'), ('SCAN_FAILED', 'Scan Failed'), ('CHECK_IN', 'Check In')], default='SCAN_SUCCESS', max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='registrations.registration')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
