# Generated by Django 6.0.2 on 2026-02-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_scanlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='student_id_card',
            field=models.ImageField(blank=True, null=True, upload_to='student_id_cards/'),
        ),
    ]
