# Generated by Django 6.0.2 on 2026-02-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_registration_student_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='bni_seats',
            field=models.IntegerField(default=141),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='public_seats',
            field=models.IntegerField(default=350),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='registration_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='students_seats',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='total_seats',
            field=models.IntegerField(default=541),
        ),
    ]
