# Generated by Django 6.0.2 on 2026-02-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_eventsettings_bni_seats_eventsettings_public_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='booking_group_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_primary_booker',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='primary_booker_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='primary_booker_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='primary_booker_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
