# Generated by Django 6.0.2 on 2026-02-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_otpverification_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='sponsor_type',
            field=models.CharField(blank=True, choices=[('PLATINUM', 'Platinum Sponsor'), ('GOLD', 'Gold Sponsor'), ('SILVER', 'Silver Sponsor'), ('BRONZE', 'Bronze Sponsor'), ('EXHIBITOR', 'Exhibitor'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
