# Generated by Django 6.0.2 on 2026-02-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_registration_sponsor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='sponsor_type',
            field=models.CharField(blank=True, choices=[('TITLE_SPONSORS', 'Title Sponsors'), ('ASSOCIATE_SPONSORS', 'Associate Sponsors'), ('CO_SPONSORS', 'Co Sponsors'), ('BNI_MEMBERS', 'BNI Members'), ('PLATINUM', 'Platinum Sponsor'), ('GOLD', 'Gold Sponsor'), ('SILVER', 'Silver Sponsor'), ('BRONZE', 'Bronze Sponsor'), ('EXHIBITOR', 'Exhibitor'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
