# Generated by Django 6.0.2 on 2026-02-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_alter_registration_sponsor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TITLE_SPONSORS', 'Title Sponsors'), ('ASSOCIATE_SPONSORS', 'Associate Sponsors'), ('CO_SPONSORS', 'Co Sponsors')], db_index=True, max_length=30)),
                ('logo_url', models.TextField(help_text='Google Drive share link URL')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['category', 'is_active', 'display_order'], name='registratio_categor_a8e2c5_idx')],
            },
        ),
    ]
