# Generated by Django 6.0.2 on 2026-02-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BNIMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('chapter', models.CharField(choices=[('BNI_CHETTINAD', 'BNI Chettinad'), ('BNI_THALAIVAS', 'BNI Thalaivas'), ('BNI_MADURAI', 'BNI Madurai')], db_index=True, max_length=20)),
                ('sponsor_type', models.CharField(choices=[('TITLE_SPONSORS', 'Title Sponsors'), ('ASSOCIATE_SPONSORS', 'Associate Sponsors'), ('CO_SPONSORS', 'Co Sponsors'), ('BNI_MEMBERS', 'BNI Members'), ('PLATINUM', 'Platinum Sponsor'), ('GOLD', 'Gold Sponsor'), ('SILVER', 'Silver Sponsor'), ('BRONZE', 'Bronze Sponsor'), ('EXHIBITOR', 'Exhibitor'), ('OTHER', 'Other')], default='BNI_MEMBERS', max_length=20)),
                ('ticket_limit', models.IntegerField(default=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['chapter', 'name'],
                'indexes': [models.Index(fields=['name', 'chapter', 'is_active'], name='registratio_name_cc157d_idx')],
                'unique_together': {('name', 'chapter')},
            },
        ),
    ]
