# Generated by Django 6.0.2 on 2026-02-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_bnimember'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorTicketLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_type', models.CharField(choices=[('TITLE_SPONSORS', 'Title Sponsors'), ('ASSOCIATE_SPONSORS', 'Associate Sponsors'), ('CO_SPONSORS', 'Co Sponsors'), ('BNI_MEMBERS', 'BNI Members'), ('PLATINUM', 'Platinum Sponsor'), ('GOLD', 'Gold Sponsor'), ('SILVER', 'Silver Sponsor'), ('BRONZE', 'Bronze Sponsor'), ('EXHIBITOR', 'Exhibitor'), ('OTHER', 'Other')], db_index=True, max_length=20, unique=True)),
                ('ticket_limit', models.IntegerField(default=2, help_text='Total number of tickets allowed (including primary member)')),
                ('description', models.TextField(blank=True, help_text='Description of sponsor benefits', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsor Ticket Limit',
                'verbose_name_plural': 'Sponsor Ticket Limits',
                'ordering': ['-ticket_limit', 'sponsor_type'],
            },
        ),
    ]
