# Generated by Django 6.0.2 on 2026-02-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_alter_registration_age_alter_registration_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='referred_by',
            field=models.CharField(blank=True, choices=[('BNI_MEMBERS', 'BNI Members'), ('FLEX', 'Flex'), ('SOCIAL_MEDIA', 'Social Media'), ('FRIENDS', 'Friends')], max_length=20, null=True),
        ),
    ]
