# Generated by Django 6.0.2 on 2026-02-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_registration_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='gateway_verified',
            field=models.BooleanField(default=False, help_text='True if payment was confirmed by payment gateway (has payment_id)'),
        ),
    ]
