# Generated by Django 6.0.2 on 2026-02-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_registration_gateway_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='message_copied',
            field=models.BooleanField(default=False, help_text='True if WhatsApp message was copied'),
        ),
        migrations.AddField(
            model_name='registration',
            name='message_copied_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when message was copied', null=True),
        ),
    ]
