# Generated by Django 6.0.2 on 2026-02-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_registration_message_copied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('STUDENTS', 'Students'), ('BNI_MEMBERS', 'BNI Members'), ('VIP', 'VIP'), ('PUBLIC', 'Public'), ('ORGANISERS', 'Organisers'), ('VOLUNTEERS', 'Volunteers')], db_index=True, help_text='Category type for this ID card template', max_length=20, unique=True)),
                ('template_url', models.TextField(blank=True, help_text='Google Drive share link URL for the ID card template PNG', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ID Card Template',
                'verbose_name_plural': 'ID Card Templates',
                'ordering': ['category'],
            },
        ),
    ]
