# Generated by Django 6.0.2 on 2026-02-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_idcardtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcardtemplate',
            name='category',
            field=models.CharField(choices=[('STUDENTS', 'Students'), ('BNI_MEMBERS_PRIMARY', 'BNI Members (Primary)'), ('BNI_MEMBERS_GUEST', 'BNI Guests'), ('BNI_MEMBERS', 'BNI Members (Legacy)'), ('VIP', 'VIP'), ('PUBLIC', 'Public'), ('ORGANISERS', 'Organisers'), ('VOLUNTEERS', 'Volunteers')], db_index=True, help_text='Category type for this ID card template', max_length=20, unique=True),
        ),
    ]
