# Generated by Django 6.0.2 on 2026-02-17 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0020_alter_idcardtemplate_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Overall event experience (1-5 stars)')),
                ('venue_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Venue quality', null=True)),
                ('food_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Food & beverages', null=True)),
                ('speaker_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Speaker/presentation quality', null=True)),
                ('networking_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Networking opportunities', null=True)),
                ('organization_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Event organization', null=True)),
                ('recommendation_score', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='How likely to recommend to others? (0-10)', null=True)),
                ('liked_most', models.TextField(blank=True, help_text='What did you like most about the event?', null=True)),
                ('improvements', models.TextField(blank=True, help_text='What could be improved?', null=True)),
                ('additional_comments', models.TextField(blank=True, help_text='Any additional comments or suggestions', null=True)),
                ('attend_future', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], help_text='Would you attend future events?', max_length=10, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of submitter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device info', null=True)),
                ('registration', models.OneToOneField(help_text='One feedback per registration', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='registrations.registration')),
            ],
            options={
                'verbose_name': 'Event Feedback',
                'verbose_name_plural': 'Event Feedback',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
