# Generated by Django 6.0.2 on 2026-02-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0021_eventfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_for',
            field=models.CharField(choices=[('BNI_THALAIVAS', 'BNI Members - Thalaivas'), ('BNI_CHETTINAD', 'BNI Members - Chettinad'), ('BNI_MADURAI', 'BNI Members - Madurai'), ('PUBLIC', 'Public'), ('STUDENTS', 'Students'), ('VIP', 'VIP'), ('ORGANISERS', 'Organisers'), ('VOLUNTEERS', 'Volunteers')], max_length=20),
        ),
    ]
