# Generated by Django 6.0.2 on 2026-02-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0022_add_vip_registration_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
