# Generated by Django 6.0.2 on 2026-02-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0023_allow_blank_location_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventfeedback',
            name='additional_comments',
        ),
        migrations.RemoveField(
            model_name='eventfeedback',
            name='food_rating',
        ),
        migrations.RemoveField(
            model_name='eventfeedback',
            name='improvements',
        ),
        migrations.RemoveField(
            model_name='eventfeedback',
            name='liked_most',
        ),
        migrations.RemoveField(
            model_name='eventfeedback',
            name='networking_rating',
        ),
        migrations.RemoveField(
            model_name='eventfeedback',
            name='organization_rating',
        ),
        migrations.RemoveField(
            model_name='eventfeedback',
            name='recommendation_score',
        ),
        migrations.RemoveField(
            model_name='eventfeedback',
            name='venue_rating',
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='attend_future',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'May be')], default='MAYBE', help_text='R u willing to join in BNI Chettinad?', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='speaker_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='Speaker quality (1-5 stars)'),
        ),
    ]
